apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pygoat-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: pygoat-test.cad4devops.com
    http:
      paths:
      - backend:
          service:
            name: pygoat-svc
            port:
              number: 80
        path: /
        pathType: Prefix